# Generated by Django 4.0.1 on 2022-02-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
